require('dotenv').config()

let { ALLOWED, DISALLOWED } = process.env;
ALLOWED = JSON.parse(ALLOWED), DISALLOWED = JSON.parse(DISALLOWED);

const { 
    EXCHANGE_1, PAGE_URL_1, API_URL_1, API_URL_BUILDER_1, 
    EXCHANGE_2,PAGE_URL_2, API_URL_2, API_URL_BUILDER_2,
    TOPIC_ARN
} = process.env;

module.exports = { 
    ALLOWED, DISALLOWED,TOPIC_ARN,
    EXCHANGE_1, PAGE_URL_1, API_URL_1, API_URL_BUILDER_1, 
    EXCHANGE_2,PAGE_URL_2, API_URL_2, API_URL_BUILDER_2,
}