require('dotenv').config()

let { ALLOWED, DISALLOWED } = process.env;
ALLOWED = JSON.parse(ALLOWED), DISALLOWED = JSON.parse(DISALLOWED);

const { 
    EXCHANGE_1, PAGE_URL_1, API_URL_1, API_URL_BUILDER_1, 
    EXCHANGE_2,PAGE_URL_2, API_URL_2, API_URL_BUILDER_2 
} = process.env;

const SEPARATOR = '<|Split|>';

module.exports = { 
    ALLOWED, DISALLOWED,SEPARATOR,
    EXCHANGE_1, PAGE_URL_1, API_URL_1, API_URL_BUILDER_1, 
    EXCHANGE_2,PAGE_URL_2, API_URL_2, API_URL_BUILDER_2,
}